### ISSUE TITLE
How to make a new world and render it?

### ISSUE THREAD

**Issue by Ploppz** [jeffparsons/planetkit#15]
I want to create a globe and render it. Here's a start:
```rust
extern crate planetkit as pk;
use pk::globe::*;
use pk::camera::*;
use pk::cell_dweller::AutoResource;

fn main() {

    let mut app = pk::AppBuilder::new()
        .build_gui();
    {
        let world = app.world_mut();
        let globe = Globe::new_earth_scale_example();
        world.create_entity().with(globe);
        let cam = DefaultCamera::new(world);
        world.add_resource(cam);
    }

    app.run();
}
```
I didn't expect it to work. What do I have to do next to render the world?

**Comment by jeffparsons** [comment]
Check out `create_simple_globe_now` in https://github.com/jeffparsons/planetkit/blob/master/planetkit/src/simple.rs for an example of how to create a globe that'll actually render. I'm on mobile right now, so I'm not sure even that will work. 😅

The API for making this stuff is pretty rubbish right now, because you have to somehow know all the components required to make a particular kind of entity "complete". Probably an easy point for improvement would be to make builders for big ticket entity types.

**Comment by jeffparsons** [comment]
A bit more detail...

```rust
let cam = DefaultCamera::new(world);
world.add_resource(cam);
```

By itself won't do much. All this does is register a resource to hold a reference to the default camera to use for rendering — but without actually creating any such camera.

Worse news: even if you create a camera and parent it on your globe, you still won't be able to see 
anything. Firstly, by default there are no systems added to the App, so you can do something like...

```rust
    let mut app = pk::AppBuilder::new()
        .add_common_systems()
        .build_gui();
```

One of the systems this will add is the `ChunkSystem` which is responsible for loading relevant chunks of the globe. This will only load areas of the globe "interesting", and currently the only concept of what is "interesting" is if there's a CellDweller sitting there. So for now the realistic ways of getting up and running probably look like...

### 1: Use `simple` to set up everything, and then once you have opinions about what you'd like to change, copy+paste the things that it calls and modify them. From https://github.com/jeffparsons/planetkit/blob/master/webdemo/src/main.rs:

```rust
extern crate planetkit as pk;

fn main() {
    let mut app = pk::AppBuilder::new()
        .add_common_systems()
        .build_gui();
    pk::simple::populate_world(app.world_mut());
    app.run();
}
```

(That's a complete app, that will run.)

### 2: Draw inspiration from my nascent single-player demo "Woolgather": https://github.com/jeffparsons/planetkit/tree/master/woolgather/src

This has its own "GameSystem" and starts to demonstrate how you might extend the boilerplate stuff provided by PlanetKit itself.

Definitely have a look at how https://github.com/jeffparsons/planetkit/blob/master/planetkit/src/simple.rs glues everything together.

I recognise that this is all super-confusing and hard to use at the moment. If you do end up playing around with it anyway, I'd love to hear any feedback you have. :)

**Comment by jeffparsons** [comment]
Closing this for now. If you have any follow-up questions, please feel free to re-open or open a new issue. :)
